### ISSUE TITLE
Add "Open in MATLAB Online" badge to StackSplit repository / README?

### ISSUE THREAD

**Issue by yvonnefroehlich** [michaelgrund/stacksplit#18]
I am wondering whether it could make sense to add a ![Open in MATLAB Online](https://www.mathworks.com/images/responsive/global/open-in-matlab-online.svg) badge to the README of the StackSplit repository (even SplitLab does not have this option).

This is based on the post [Open science and reusable research with MATLAB Online and GitHub](https://blogs.mathworks.com/matlab/2023/07/20/open-science-and-reusable-research-with-matlab-online-and-github/) on "The MATLAB Blog". Users need a MATLAB account but not a MATLAB license.

I have started to test this with my repository `sws-visualization-and-modeling` to figure out how helpful it could be for running, modifying, and maintaining MATLAB code.

matlab.mathworks.com/open/github/v1?repo=yvonnefroehlich/sws-visualization-and-modeling

![matlab_online_test_swsmod](https://github.com/michaelgrund/stacksplit/assets/94163266/9c61c50a-88a5-468f-96c2-b83274e7d6e0)

**Comment by michaelgrund** [comment]
In principle I like this idea to support reproducibility of results. However, since StackSplit does not run without SplitLab, I cannot see how this should work on this platform.
