### ISSUE TITLE
Upcoming change in saving figures of UIs via "print": Control saved figure of SplitLab diagnostic plot

### ISSUE THREAD

**Issue by yvonnefroehlich** [michaelgrund/stacksplit#23]
_First reported at_: https://github.com/michaelgrund/stacksplit/pull/13#issuecomment-1793497584

Upon MATLAB R2023b, a warning regarding saving the diagnostic plot produced by **SplitLab** is raised:
```
Warning: In a future release, UI components will not be included in the
output. To include UI components, use the exportapp function. 
> In print (line 86)
In saveresult (line 114) 
```
_SplitLab 1.0.5_:
https://github.com/michaelgrund/stacksplit/blob/0bbf2edb936e4e895365be5462ad5c24dd32d032/StackSplit/SL_mod/SL_1.0.5_mod/saveresult_SS.m#L120

_SplitLab 1.2.1_:
https://github.com/michaelgrund/stacksplit/blob/0bbf2edb936e4e895365be5462ad5c24dd32d032/StackSplit/SL_mod/SL_1.2.1_mod/saveresult_SS.m#L114

This warning is not raised when saving the diagnostic plot of the **SIMW** produced by **StackSplit**:
https://github.com/michaelgrund/stacksplit/blob/0bbf2edb936e4e895365be5462ad5c24dd32d032/StackSplit/SS_saveresults.m#L410-L417

So far, MATLAB has not stated in which release this change will be applied.

This issue is a reminder to
- [ ] compare the diagnostic plots and the saving of the corresponding figures between SplitLab and StackSplit.
- [ ] not forget this warning when updating to R2024a and higher (i. e., also check the modified SplitLab functions).
- [ ] check for missing features of the SplitLab diagnostic plot in the saved figure upon the release in which this change is applied, and if yes, decide about appropriate code changes.

**Comment by yvonnefroehlich** [comment]
@michaelgrund, I just saw that the pre-release of MATLAB R2024a is now available 🙂🎉🚀.

_**My questions is now**_: Should changes releated to R2024a be included in the release of v3.1, i. e., does it make sense that I start working on this (I first have to install it and then check if there are any new issues) or is this something we we want to do later and include any changes related to R2024a in the release after next?

_**Edit 2024/01/07**_: I started working on this. So far it looks like there are no R2024a related problems 🙂. For StackSplit, there is only one new suggestion, for which I submitted PR #25.

_**Edit 2024/04/09**_: MATLAB 2024a is now available. I installed this version and so far I still do not face any R2024a-related problems (under Windows).

**Comment by yvonnefroehlich** [comment]
The pre-release of MATLAB R2024b is available!

I installed this MATLAB version and tested StackSplit under Windows, and so far there seem to be no new issues regarding StackSplit. There are only some minor differences in the appearance of the StackSplit start window:

| R2024a [Linux] | R2024b pre-release [Windows] |
| --- | --- |
| ![stacksplit_startwindow_R2024a_linux](https://github.com/michaelgrund/stacksplit/assets/94163266/bccf643a-955f-4237-9acc-2f9a491fc6a0) | ![stacksplit_startwindow_R2024b_prerelease_windows](https://github.com/michaelgrund/stacksplit/assets/94163266/5137874b-4628-415c-8cd2-54f1e1166bfa) |

**Comment by michaelgrund** [comment]
So we don't need to justify anything for that, right?

**Comment by yvonnefroehlich** [comment]
> So we don't need to justify anything for that, right?

Yes, so far I do not face any issues related to R2024b using the pre-release under Windows. I only have a pre-release license for Windows, but I do not expect any OS-related issues. I checked if the normal usage works as expected (not every minor detail), but normally the changes between the Rxxxxa and the Rxxxxb releases are smaller.
